<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "beusertools"
 *
 * Auto generated by Extension Builder 2014-11-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Download Statistics',
	'description' => 'Logs file downloads through EXT:fal_securedownload',
	'category' => 'module',
	'author' => 'Lorenz Ulrich',
	'author_email' => 'lorenz.ulrich@visol.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
    'autoload' =>
        array(
            'psr-4' => array('Visol\\DownloadStats\\' => 'Classes')
        ),
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);